remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Sofia Meroni
description: Porfolio de Sofia.
url: https://tu-usuario.github.io/SofiaMeroni.github.io
baseurl: /SofiaMeroni.github.io  
