title: Sofia Meroni
description: Mi porfolio.
theme: jekyll-theme-cayman
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
logo_url: https://github.githubassets.com/images/icons/emoji/octocat.png
