title: sofia  # Título de tu sitio
description: adios.  # Descripción de tu sitio
show_downloads: false
#icono
head:
  - '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">'

<i class="fa-thin fa-crow"></i>