# Site settings
title: Sofia Meroni
description: QA Automation Enginner – Quality Assurance Engineer
author: Sofia Meroni (SofiaMEroni)
url: https://sofiameroni.github.io/SofiaMeroni/
repository: https://github.com/SofiaMeroni/SofiaMeroni

theme: just-the-docs
favicon_ico: "assets\Foto.jpg"

# Optional features
# Enable or disable the site search
#search_enabled: false
# For copy button on code
#enable_copy_code_button: true

  
# External navigation links
nav_external_links:
  - title: GitHub
    url: https://github.com/SofiaMeroni
  - title: LinkedIn
    url: www.linkedin.com/in/sofiameroni 
    
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red