title: sofia  # Título de tu sitio
description: adios.  # Descripción de tu sitio
show_downloads: true  # Mostrar enlaces de descarga

remote_theme: pages-themes/cayman@v0.2.0  # Tema remoto Cayman

color:  # Personalización de colores
  header: "#f5bba4"
  gradient_left: "#2be194"
  gradient_right: "#ed642d"

logo_url:  # URL del logo

syntax_theme: <i class="fa-thin fa-crow"></i>  # Tema de sintaxis

buttons:  # Configuración de botones
  zip_url: https://github.com/SofiaMeroni/SofiaMeroni.github.io/blob/main/_config.yml
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true