name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Check code formatting with Black
        run: |
          if [ -d scripts ]; then black --check scripts; fi
          if [ -d tests ]; then black --check tests; fi
        continue-on-error: true
        
      - name: Lint with flake8
        run: |
          if [ -d scripts ]; then flake8 scripts --count --select=E9,F63,F7,F82 --show-source --statistics; fi
          if [ -d tests ]; then flake8 tests --count --select=E9,F63,F7,F82 --show-source --statistics; fi
        continue-on-error: true
        
      - name: Static code analysis with Pylint
        run: |
          if [ -d scripts ]; then pylint --disable=C0111,C0103,C0303 scripts; fi
          if [ -d tests ]; then pylint --disable=C0111,C0103,C0303 tests; fi
        continue-on-error: true
        
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          
      - name: Check for security vulnerabilities with Bandit
        run: |
          if [ -d scripts ]; then bandit -r scripts -f txt; fi
          if [ -d tests ]; then bandit -r tests -f txt -s B101; fi
        continue-on-error: true
        
      - name: Check dependencies for known vulnerabilities
        run: safety check -r requirements.txt
        continue-on-error: true
        
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Test with pytest
        run: |
          if [ -d tests ]; then pytest --cov=./ --cov-report=xml; fi
        continue-on-error: true
          
  validate_html:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          
      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install
          
      - name: Build Jekyll site
        run: bundle exec jekyll build
        continue-on-error: true