name: Docker Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3
      
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verificar versión de Buildx
        run: docker buildx version
      
      - name: Construir la imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: sofiameroni/personal-website:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
