name: Docker Build

on:
  push:
    branches: [ main ] # Ejecuta este workflow cuando se haga push a la rama main
    tags: [ 'v*' ] # También se ejecuta cuando se crea un tag que comience con 'v'

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente # Obtiene el código fuente del repositorio
        uses: actions/checkout@v3
      
      - name: Configurar Docker Buildx # Habilita Docker Buildx para compilaciones avanzadas
        uses: docker/setup-buildx-action@v2

      - name: Verificar versión de Buildx # Verifica que Buildx está instalado y funcionando
        run: docker buildx version
      
      - name: Construir la imagen Docker # Construye la imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: . # Usa el directorio actual como contexto de construcción
          push: false  # No sube la imagen a Docker Hub 
          tags: sofiameroni/personal-website:latest # Etiqueta de la imagen
          cache-from: type=gha # Usa caché de GitHub Actions
          cache-to: type=gha,mode=max # Guarda caché para futuras ejecuciones

      # Subir la imagen a Docker Hub
      - name: Iniciar sesión en Docker Hub # Se autentica en Docker Hub y el siguiente if Solo si el push es a la rama main
        if: github.ref == 'refs/heads/main' 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Verificar login en Docker Hub (Paso nuevo)
      - name: Verificar login en Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker info

      - name: Publicar imagen en Docker Hub # Sube la imagen a Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: . # Usa el directorio actual como contexto de construcción
          push: true  # Cambia a true si deseas subir la imagen a Docker Hub
          tags: sofiameroni/personal-website:latest
          cache-from: type=gha # Usa caché para acelerar la construcción
          cache-to: type=gha,mode=max # Guarda caché para futuras ejecuciones
